version: '3.6'

services:
  db:
    image: mysql:5
    env_file: .env
    restart: always
    volumes:
      - ${HOMESERVER_DIR}/docker/ninja/db:/var/lib/mysql
    networks:
      - default

  app:
    image: invoiceninja/invoiceninja
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      -  ${HOMESERVER_DIR}/docker/ninja/storage:/var/www/app/storage
      -  ${HOMESERVER_DIR}/docker/ninja/logo:/var/www/app/public/logo
      -  ${HOMESERVER_DIR}/docker/ninja/public:/var/www/app/public
    networks: 
      - default  

  web:
    image: nginx:1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      -  ${HOMESERVER_DIR}/docker/ninja/storage:/var/www/app/storage
      -  ${HOMESERVER_DIR}/docker/ninja/logo:/var/www/app/public/logo
      -  ${HOMESERVER_DIR}/docker/ninja/public:/var/www/app/public
    expose: # Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.
      - "80"
    depends_on:
      - app
    ports: # Delete if you want to use reverse proxy
      - 9016:80
    networks:
#      - web        # uncomment if you want to use  external network (reverse proxy for example)
      - default


  cron:
    image: invoiceninja/invoiceninja
    env_file: .env
    volumes:
      -  ${HOMESERVER_DIR}/docker/ninja/storage:/var/www/app/storage
      -  ${HOMESERVER_DIR}/docker/ninja/logo:/var/www/app/public/logo
      -  ${HOMESERVER_DIR}/docker/ninja/public:/var/www/app/public
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    networks:
      - default
