version: "3.6"

services:
  drone:
    image: drone/drone:1
    ports:
      - 9017:80
      - 9018:443
    restart: always
    volumes:
      - ./data:/data
    env_file:
      - env/drone.env

  drone-runner:
    image: drone/drone-runner-docker:1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - env/drone-runner.env
    ports:
      - 3000:3000
    depends_on:
      - drone
