version: "3.6"
services:
  minecraft-server:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      SERVER_NAME: kjuulh-vanilla
      EULA: "TRUE"
    volumes:
      - ${HOMESERVER_DIR}/docker/minecraft-vanilla:/data
    container_name: mc
    tty: true
    stdin_open: true
    restart: always

  # minecraft-server-ftb:
  #   image: itzg/minecraft-server
  #   ports:
  #     - "25566:25565"
  #   environment:
  #     TYPE: FTB
  #     FTB_SERVER_MOD: https://www.feed-the-beast.com/projects/ftb-revelation/files/2712063
  #     SERVER_NAME: kjuulh-ftb
  #     EULA: "TRUE"
  #   volumes:
  #     - ${HOMESERVER_DIR}/docker/minecraft-ftb:/data
  #   container_name: mc-ftb
  #   tty: true
  #   stdin_open: true
  #   restart: always